Feature/partners 1004 add modal for v1
Bestowinc/protect-lite pull request #30
Opened 2022-03-18 16:17 UTC by tcorkran

2022-03-18 17:16 UTC, mikeb333 requested changes
Looks good to me. Just one suggestion for ensuring the modal is centered.

2022-03-18 17:16 UTC, mikeb333 commented on src/static/v1/iframe/modal/styles.css
> +    left: 40%;
I believe if we set the css like below then it will ensure the modal is always centered...

```html
left: 0;
right: 0;
margin: 0 auto;
```

2022-03-21 13:28 UTC, tcorkran commented on src/static/v1/iframe/modal/styles.css
> +    left: 40%;
Unfortunately that wont work for a modal. The position cannot be block or table as the page layout would interfere with the modal and utilizing margin 0 auto requires that. The problem I'm having and what you are experiencing is getting it to center when the width is flexible, On my screen where the screen is wide enough to trigger the max 20% width, it is perfectly centered. On yours that is less than 20%, it appears offset. I am currently working on this issue.

2022-03-21 22:19 UTC, mikeb333 approved these changes

2022-03-22 17:00 UTC, mikeb333 approved these changes

2022-03-23 20:14 UTC, merged